use crate::shared::errors::DomainError;

#[derive(Debug, Clone)]
pub enum MaterialCodePolicy {
    AutoGenerated { category_id: String },
    Manual(String),
}

pub struct CodeGenerator;

impl CodeGenerator {
    /// Generates a sequential code according to the pattern:
    /// a0..a9, then a00..a99, then a000..a999, etc.
    pub fn generate_sequential_code(prefix: &str, sequence: u64) -> Result<String, DomainError> {
        if prefix.trim().is_empty() {
            return Err(DomainError::Invalid(
                "بادئة الكود لا يمكن أن تكون فارغة".into(),
            ));
        }

        let prefix = prefix.trim();
        let mut seq = sequence;
        let mut digits = 1;
        let mut range = 10;

        while seq >= range {
            seq -= range;
            digits += 1;
            range *= 10;
        }

        Ok(format!("{}{:0width$}", prefix, seq, width = digits))
    }

    /// Generates a hybrid code by joining multiple prefixes and adding a sequence.
    /// e.g. ["أ", "a", "0"] -> "أ-a-0-seq"
    pub fn generate_hybrid_code(prefixes: Vec<String>, sequence: u64) -> Result<String, DomainError> {
        if prefixes.is_empty() {
            return Err(DomainError::Invalid("يجب توفر بادئة واحدة على الأقل".into()));
        }

        let combined_prefix = prefixes.join("-");
        Self::generate_sequential_code(&combined_prefix, sequence)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_sequential_code() {
        // Length 1 (0-9)
        assert_eq!(CodeGenerator::generate_sequential_code("A", 0).unwrap(), "A0");
        assert_eq!(CodeGenerator::generate_sequential_code("A", 9).unwrap(), "A9");
        
        // Length 2 (10-109 -> 00-99)
        assert_eq!(CodeGenerator::generate_sequential_code("A", 10).unwrap(), "A00");
        assert_eq!(CodeGenerator::generate_sequential_code("A", 109).unwrap(), "A99");
        
        // Length 3 (110-1109 -> 000-999)
        assert_eq!(CodeGenerator::generate_sequential_code("A", 110).unwrap(), "A000");
        assert_eq!(CodeGenerator::generate_sequential_code("A", 1109).unwrap(), "A999");
    }

    #[test]
    fn test_generate_hybrid_code() {
        let prefixes = vec!["أ".to_string(), "a".to_string(), "0".to_string()];
        assert_eq!(
            CodeGenerator::generate_hybrid_code(prefixes, 0).unwrap(),
            "أ-a-00"
        );
    }
}
