[package]
name = "tauri-adapter"
version = "0.9.6"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["wry", "custom-protocol"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
rust_decimal = "1.33"
uuid = { version = "1.6", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.13.2", features = ["json", "stream"] }
futures-util = "0.3"
sha2 = "0.10"

domain = { path = "../domain" }
application = { path = "../application" }
infrastructure = { path = "../infrastructure" }
tauri-plugin-dialog = "2.7.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
