#!/usr/bin/env node
/**
 * Workspace Rust watcher (zero dependencies).
 *
 * Runs alongside `tauri dev` and bridges the gap between Tauri's built-in dev
 * watcher — which only watches the app dir (`apps/desktop/src-tauri`) — and the
 * real Rust sources in `crates/*` (domain / application / infrastructure /
 * tauri-adapter).
 *
 * On any change to a `.rs` or `Cargo.toml` under `crates/`, it rewrites an
 * inert, git-ignored marker file inside `src-tauri/src`. Tauri's dev CLI sees
 * the change, re-runs `cargo build` (recompiling the touched crates and
 * relinking the `desktop` binary) and restarts the app process — so editing any
 * shared Rust crate is EDIT → CARGO REBUILD → TAURI RESTART → CONTINUE, no
 * manual `pnpm build` needed. The DB never resets: restarts keep the same
 * app-data DB.
 *
 * Implementation: Node >= 20 recursive `fs.watch` on Windows/macOS, with a
 * cheap mtime polling fallback if the native recursive watch is unavailable.
 */

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const cratesRoot = path.join(root, 'crates');
const markerFile = path.join(root, 'apps', 'desktop', 'src-tauri', 'src', 'watch_touch.rs');

// Files outside crates/ that still force a rebuild when edited: the workspace
// manifest (members / workspace.dependencies) and (if present) cargo config.
const extraWatchFiles = [
  path.join(root, 'Cargo.toml'),
  path.join(root, '.cargo', 'config.toml'),
].filter((f) => fs.existsSync(f));

const DEBOUNCE_MS = 300;
const POLL_MS = 1000;

let touchCounter = 0;
let pending = false;
let washTimer = null;

function isTargetName(name) {
  const lower = path.extname(name).toLowerCase();
  return lower === '.rs' || name === 'Cargo.toml';
}

function markerContent() {
  const value = `${Date.now()}_${touchCounter++}`;
  return [
    '// Generated by scripts/watch-crates.js — do not edit.',
    `// (${new Date().toISOString()})`,
    '// This file is intentionally NOT part of the desktop crate module tree; it',
    "// exists only to poke Tauri's dev file watcher so edits to workspace crates",
    '// (crates/*) trigger a cargo rebuild + app restart.',
    '#![allow(unused)]',
    '',
    'pub const CRATES_TOUCH: &str = "',
    value,
    '";',
    '',
  ].join('\n');
}

function writeMarker() {
  try {
    fs.mkdirSync(path.dirname(markerFile), { recursive: true });
    fs.writeFileSync(markerFile, markerContent(), 'utf8');
    console.log(
      `[watch-crates] change detected -> touched ${path
        .relative(root, markerFile)
        .replace(/\\/g, '/')} (Tauri will rebuild + restart)`,
    );
  } catch (err) {
    // Marker writes must never kill the dev session; the next change retries.
    console.warn(`[watch-crates] failed to write marker: ${err.message}`);
  }
}

function schedule() {
  if (pending) return;
  pending = true;
  washTimer = setTimeout(() => {
    pending = false;
    washTimer = null;
    writeMarker();
  }, DEBOUNCE_MS);
}

/** Debounce + collapse bursts (cargo/rust-analyzer rewrite many files fast). */
function handleEvent(eventType, filename) {
  if (!filename) return;
  if (typeof filename !== 'string') filename = String(filename);
  // A brand-new crate directory (rename/rename:dir) brings a Cargo.toml with
  // it — schedule so the new workspace member is picked up immediately.
  if (eventType && eventType.startsWith('rename')) {
    const abs = path.isAbsolute(filename) ? filename : path.join(cratesRoot, filename);
    try {
      if (fs.statSync(abs).isDirectory() && fs.existsSync(path.join(abs, 'Cargo.toml'))) {
        schedule();
        return;
      }
    } catch {
      /* stat race — the entry vanished; keep filtering by name below */
    }
  }
  if (path.isAbsolute(filename)) filename = path.relative(cratesRoot, filename);
  if (!isTargetName(filename)) return;
  schedule();
}

/** Watch a single extra file (root Cargo.toml, .cargo/config.toml). Falls back
 *  to a cheap mtime poll if the native file watcher is unavailable. */
function watchExtraFile(file) {
  const onError = (err) => {
    console.warn(`[watch-crates] file watcher for ${path.basename(file)} unavailable (${err.message}); polling`);
  };
  try {
    const w = fs.watch(file, { persistent: true }, (eventType) => {
      if (eventType === 'change' || eventType === 'rename') schedule();
    });
    w.on('error', onError);
  } catch (err) {
    onError(err);
    let lastMtime = 0;
    setInterval(() => {
      let mtime = 0;
      try {
        mtime = fs.statSync(file).mtimeMs;
      } catch {
        return;
      }
      if (lastMtime && lastMtime !== mtime) schedule();
      lastMtime = mtime;
    }, POLL_MS);
  }
}

/** Shallow mtime-based fallback for platforms/archives without recursive watch. */
function startPolling() {
  let lastSeen = new Map();
  const scan = () => {
    const now = new Map();
    const walk = (dir) => {
      let entries;
      try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
      } catch {
        return;
      }
      for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          walk(full);
        } else if (isTargetName(entry.name)) {
          let mtime = 0;
          try {
            mtime = fs.statSync(full).mtimeMs;
          } catch {
            /* file vanished */
          }
          now.set(full, mtime);
        }
      }
    };
    walk(cratesRoot);
    // Also track the extra out-of-tree files (root Cargo.toml, cargo config).
    for (const file of extraWatchFiles) {
      try {
        now.set(file, fs.statSync(file).mtimeMs);
      } catch {
        /* file vanished */
      }
    }
    for (const [file, mtime] of now) {
      const before = lastSeen.get(file);
      if (before !== undefined && before !== mtime) {
        schedule();
        break;
      }
    }
    lastSeen = now;
  };
  scan();
  setInterval(scan, POLL_MS);
}

function bootstrapMarker() {
  if (!fs.existsSync(markerFile)) writeMarker();
}

function main() {
  bootstrapMarker();
  if (!fs.existsSync(cratesRoot)) {
    console.warn(`[watch-crates] ${cratesRoot} does not exist — nothing to watch.`);
    return;
  }
  let native = null;
  try {
    native = fs.watch(cratesRoot, { recursive: true }, handleEvent);
    native.on('error', (err) => {
      console.warn(`[watch-crates] native watcher error: ${err.message}; falling back to polling`);
      native?.close();
      native = null;
      startPolling();
    });
    console.log(`[watch-crates] watching ${path.relative(root, cratesRoot).replace(/\\/g, '/')}/ for changes`);
    for (const file of extraWatchFiles) {
      watchExtraFile(file);
      console.log(`[watch-crates] watching ${path.relative(root, file).replace(/\\/g, '/')} for changes`);
    }
  } catch (err) {
    console.warn(`[watch-crates] recursive watch unavailable: ${err.message}; using polling`);
    startPolling();
  }
  // Never let the process linger; dev.js owns the lifecycle.
  process.on('SIGINT', () => process.exit(0));
  process.on('SIGTERM', () => process.exit(0));
}

module.exports = { writeMarker, bootstrapMarker };

if (require.main === module) {
  main();
}