#[derive(sqlx::FromRow)]
pub struct InvoiceRow {
    pub id: String,
    pub invoice_number: String,
    pub invoice_type: String,
    pub customer_id: Option<String>,
    pub customer_name: Option<String>,
    pub supplier_id: Option<String>,
    pub supplier_name: Option<String>,
    pub tax_amount: String,
    pub tax_amount_base: String,
    pub discount_amount: String,
    pub discount_amount_base: String,
    pub extra_costs: String,
    pub extra_costs_base: String,
    pub total_amount: String,
    pub total_amount_base: String,
    pub payment_method: String,
    pub amount_paid: String,
    pub amount_paid_base: String,
    pub status: String,
    pub issued_at: String,
    pub currency_code: String,
    pub exchange_rate: String,
    pub notes: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(sqlx::FromRow)]
#[allow(dead_code)]
pub struct LineRow {
    pub id: String,
    pub invoice_id: String,
    pub material_id: String,
    pub quantity: String,
    pub unit_id: Option<String>,
    pub conversion_factor: Option<String>,
    pub unit_price: String,
    pub purchase_price: Option<String>,
    pub retail_price: Option<String>,
    pub wholesale_price: Option<String>,
    pub semi_wholesale_price: Option<String>,
    pub minimum_stock: Option<String>,
    pub warehouse_id: Option<String>,
    pub expiry_date: Option<String>,
    pub notes: Option<String>,
    pub unit_price_original: Option<String>,
    pub purchase_price_original: Option<String>,
    pub profit_amount_original: Option<String>,
}
